# Generated by Django 5.0.4 on 2024-06-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('property_id', models.CharField(max_length=30, unique=True)),
                ('property_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('starting_price', models.FloatField()),
                ('addres1', models.CharField(max_length=50)),
                ('addres2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('country', models.CharField(default='India', max_length=50)),
                ('deleted_status', models.BooleanField(default=False)),
                ('dist_from_college', models.FloatField(default=50.0)),
                ('security_charges', models.FloatField(default=0.0)),
                ('security_features', models.JSONField(default=dict)),
                ('lifestyle', models.JSONField(default=dict)),
                ('rules', models.JSONField(default=dict)),
                ('description', models.TextField(default=None, max_length=500)),
                ('cover_image', models.ImageField(upload_to='cover_image')),
                ('avl_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avl_type', to='main.dropdown')),
                ('mess_facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mess_fclty', to='main.dropdown')),
                ('near_college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='near_clg', to='main.dropdown')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_idty', to='main.ownerdetails')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppty_type', to='main.dropdown')),
                ('rnt_pay_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnt_pay', to='main.dropdown')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('total_rooms', models.PositiveSmallIntegerField()),
                ('occupied_rooms', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('furnished', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fur_inf', to='main.dropdown')),
                ('kitchen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_rel', to='main.dropdown')),
                ('ppty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppty_detail', to='properties.propertydetails')),
                ('seater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seater_inf', to='main.dropdown')),
                ('washroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_rel', to='main.dropdown')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='room_images')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_img', to='properties.roomdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anemities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amnty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amnt_idty', to='main.dropdown')),
                ('ppty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppty_amnt', to='properties.propertydetails')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_amnt', to='properties.roomdetails')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('room_no', models.PositiveSmallIntegerField()),
                ('sharing_with', models.JSONField(default=dict)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_detail', to='properties.roomdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
