# Generated by Django 5.0.4 on 2024-06-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydetails',
            old_name='addres1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='addres2',
            new_name='address2',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_id',
        ),
    ]
