# Generated by Django 5.0.4 on 2024-06-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ownerdetails_zip_code'),
        ('properties', '0002_rename_addres1_propertydetails_address1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anemities',
            new_name='Amenities',
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
