# Generated by Django 5.0.4 on 2024-06-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ownerdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
