# Generated by Django 5.0.4 on 2024-06-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ownerdetails_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerdetails',
            old_name='addres1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='ownerdetails',
            old_name='addres2',
            new_name='address2',
        ),
    ]
